<p><h1>Psuedo Code of Gaussian Elimination</h1><p>
    
<table align='left'>
    <tr>
        <td><img src = 'Pseudo_Code_of_Gaussian_Eilmination.png' width='600' height='600' ></td>
    </tr>
</table>

<p><h1>Example:</h1></p>
<table align='left'>
    <tr>
        <td><img src = 'Example.png' width='600' height='600' ></td>
    </tr>
</table>

In [108]:
def Gauss_Elim(Aug_mat):
    
    import copy as cp
    import numpy as np
    from sys import exit
    
    # Check if the input is legimate.
    n,m = len(Aug_mat), len(Aug_mat[0])
    if (m-n) != 1:
        print('Wrong Augment Matrix ...')
        exit()    
    
    else:
        for i in range(n-1):
            
            # if pivot element is non-zero, do the elimination.
            if Aug_mat[i][i] != 0:
                for j in range(i, n-1):
                    Aug_mat[j+1] = (Aug_mat[j+1] - (Aug_mat[j+1][i] / Aug_mat[i][i]) * Aug_mat[i])
    
            # else if pivot element is non-zero, do the change of permutation.
            elif Aug_mat[i][i] == 0:
                
                # Find the nearest non-zero row.
                A_tran = np.transpose(Aug_mat)
                index = np.array(np.where(A_tran[i] != 0))
                
                # If the row is found, change the permutation between new row and original zero one.
                if index != []:
                    try:
                        index = index[index > i][0]                
                        temp_a, temp_b = cp.deepcopy(Aug_mat[i]), cp.deepcopy(Aug_mat[index])
                        Aug_mat[i], Aug_mat[index] = temp_b, temp_a
                
                    # If index is not larger than i, it means the previous row is found, which has done elimination
                    except IndexError:
                        print('No unique solution exists ...')
                        break
                
                    # After permutation changing, do the elimination.
                    for j in range(i, n-1):
                        Aug_mat[j+1] = (Aug_mat[j+1] - (Aug_mat[j+1][i]/Aug_mat[i][i]) * Aug_mat[i])
            
            # Print the elimination process
            print('Aug_mat: %i' % i)
            print(Aug_mat)
            print('\n')
    
        # Check if there is a solution or not from deducted Augment Matrix
        test = list(Aug_mat[-1])[:-1]
        if any(test) != True: 
            value = Aug_mat[i][-1]
            
            # There is no unique solution
            if value == 0:
                print('No unique solution exists ...')
                exit()
            # There is no solution
            else:
                print('No solution exists ...')
                exit()
                
        # Backward Institution
        x_list = np.zeros(n)
        x_list[-1] = (Aug_mat[-1][-1]/Aug_mat[-1][-2])
        for k in range(1,n):
            i = (n-1)-k
            all_sum = 0
            for j in range(0,n):
                all_sum += (Aug_mat[i][j] * x_list[j])
            x_list[i] = (Aug_mat[i][-1] - all_sum) / Aug_mat[i][i]

        # Print out results
        if x_list[-1] != np.nan:
            print('The result:')
            for i in range(len(x_list)):
                print('X%i = %.3f' % (i+1, x_list[i]))

<p><h1>Print out results</h1></p>

In [109]:
# Input Augmented matrix
Aug_matrix = np.array([[1, -1, 2, -1, -8],
                       [2, -2, 3, -3, -20],
                       [1,  1, 1,  0, -2],
                       [1, -1, 4,  3,  4]])

Gauss_Elim(Aug_matrix)

Aug_mat: 0
[[ 1 -1  2 -1 -8]
 [ 0  0 -1 -1 -4]
 [ 0  2 -1  1  6]
 [ 0  0  2  4 12]]


Aug_mat: 1
[[ 1 -1  2 -1 -8]
 [ 0  2 -1  1  6]
 [ 0  0 -1 -1 -4]
 [ 0  0  2  4 12]]


Aug_mat: 2
[[ 1 -1  2 -1 -8]
 [ 0  2 -1  1  6]
 [ 0  0 -1 -1 -4]
 [ 0  0  0  2  4]]


The result:
X1 = -7.000
X2 = 3.000
X3 = 2.000
X4 = 2.000


/home/jordanwu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:29: DeprecationWarning: elementwise != comparison failed; this will raise an error in the future.
